### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Baracoot** [obble/modui_classic#1]
Message: Interface\AddOns\modui_classic\skin/skin.lua:29: attempt to index global 'MainMenuBarArtFrameBackground' (a nil value)
Time: Tue Jul  2 21:53:21 2019
Count: 1
Stack: Interface\AddOns\modui_classic\skin/skin.lua:29: attempt to index global 'MainMenuBarArtFrameBackground' (a nil value)
Interface\AddOns\modui_classic\skin/skin.lua:29: in main chunk

Locals: _ = "modui_classic"
addon = <table> {
 colour = <table> {
 }
}
f = <unnamed> {
 0 = <userdata>
}
(*temporary) = <table> {
}
(*temporary) = MinimapBorder {
 0 = <userdata>
}
(*temporary) = MiniMapTrackingBorder {
 0 = <userdata>
}
(*temporary) = MiniMapMailBorder {
 0 = <userdata>
}
(*temporary) = MiniMapBattlefieldBorder {
 0 = <userdata>
}
(*temporary) = PlayerFrameTexture {
 0 = <userdata>
}
(*temporary) = TargetFrameTextureFrameTexture {
 0 = <userdata>
}
(*temporary) = PetFrameTexture {
 0 = <userdata>
}
(*temporary) = PartyMemberFrame1Texture {
 0 = <userdata>
}
(*temporary) = PartyMemberFrame2Texture {
 0 = <userdata>
}
(*temporary) = PartyMemberFrame3Texture {
 0 = <userdata>
}
(*temporary) = PartyMemberFrame4Texture {
 0 = <userdata>
}
(*temporary) = PartyMemberFrame1PetFrameTexture {
 0 = <userdata>
}
(*temporary) = PartyMemberFrame2PetFrameTexture {
 0 = <userdata>
}
(*temporary) = PartyMemberFrame3PetFrameTexture {
 0 = <userdata>
}
(*temporary) = PartyMemberFrame4PetFrameTexture {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'MainMenuBarArtFrameBackground' (a nil value)"

**Comment by obble** [comment]
cheers for the report, i'll add a version check for between retail and classic tonight that should fix this.

**Comment by obble** [comment]
should be fixed in v4, please reopen this if you see the issue or one similar to it still
