### ISSUE TITLE
(sorry)! Obble

### ISSUE THREAD

**Issue by WrobotProfiles** [obble/modui_classic#11]
Im wondering if you could get in contact with me -
Andoido#0218 

Huge fan. I have a Lot of suggestions that you could maybe implement to improve Modui. Ive made my own edits for my own version and figured id atleast ask if you would hear me out!

Sorry last time ill post.
Please bring back the raid frames, and the old "unit frames - except with debuff timmers!!)

**Comment by obble** [comment]
feel free to use this open issue to drop in your feature suggestions and link to edits or improvements you've worked on.

im planning on looking at raidframes in the future, and theres some changes still to make for the unitframes - it should be fairly easy to add debuff timers via [LibClassicDurations](https://github.com/rgd87/LibClassicDurations) assuming its well built.

**Comment by WrobotProfiles** [comment]
Id ver much like to see the older style of Item Raritys - compared to the new ones that you did ( deep purple and deep green colors)

Iplementing the ImprovedUnitFrames style for the healthbars would be cool too - if your familiar with that addon!

ill add more in a bit when im not so bombed out tired

**Comment by obble** [comment]
No plans to add the older button border which the item rarity borders were based on unfortunately, it wasn't a great system for skinning buttons. You could look at [oGlow](https://www.wowinterface.com/downloads/info25098-oGlowClassic.html) as a solution maybe.

Also not planning on adding ImprovedUnitFrames styling at the moment.

Let me know your other thoughts though.

**Comment by WrobotProfiles** [comment]
Sad to hear =( i loved the way you did the item rarity colors.

Will you be including a Talent Spec guide like you did in one of your older uis?

What about the "Nameplates" - I fucking LOVED your nameplates from the original Modui, Are you going to keep thoes, maybe beef them up (include debuff, pvp rank,) etc ? I saw a pick, just thought it would be cool to have a choice between the two.

Onebag - i assume youll have an option to get rid of that, aswell as the EndCaps.


I was going to suggest some sort of Map Replacement (Cartographer) for example, uncovered all areas - currently theres not a single addon that will, or looks like it will, do this. Just show the entire map without the "Undiscovered" areas. Odd request.

Raid Frames - were amazing, i loved them! Also another "Dealers Choice" (like user can choost from)
https://www.wowace.com/projects/sraidframes
(A version that was made for vanilla )
https://github.com/satan666/sRaidFrames_Improved

Possible? Prob not rofl =p-
--------------------------------------------------

Your original modui was perfection - im looking forward to seeing what you do! adding in the stuff you did. 

THanks for all your work. ive supported you from day 1 - and have linked your ui to TONS of people. 
Thanks!!!

**Comment by obble** [comment]
Glowing borders around suggested talent specs toggled on and off would be cool, i remember laying that out as an idea but not getting it finished up - i'll look into it. Would probably have to crowd-source some other class specs outside of the ones i immediately play myself.

Nameplates are on their way to completion, the style is mostly the same and I added planned support for PvP ranks (when they are enabled) and castbars - debuff support will be added, there's some work towards it already.

One-bag can already be toggled off. I didn't add an option to hide or change the gryphons since the BfA mainbar is actually a single texture currently (this may or may not change) but I could add it for the standard classic-style bar layout.

No plan to add maps without the fog of war currently - it would add a ton of weight to the UI in terms of textures to load. 

Raidframes are planned.

**Comment by WrobotProfiles** [comment]
you rock man.
The raid frames going to be the same ? or

**Comment by obble** [comment]
Not sure at this stage - Blizzard is using a much more up-to-date version of its raidframes as far as I know, so i'm keen to get a feel for those and compare them both with the old modui frames and the [retail ones I'd previously](https://cdn-wow.mmoui.com/preview/pvw70030.png) designed for the best layout options.

**Comment by WrobotProfiles** [comment]
Those are dope.
Im excited to see what you release man - i got my guild all into your addon aswell hah.

I will miss the special loot colors though =( OGlow's are shitty compared to what you had!

**Comment by obble** [comment]
it just makes it smaller and easier to pop up in the game without affecting movement (removing the blackout background etc), adds coordinates for cursor and player, and modifies the party/raid blip icons with class colours and other info. No plans to show unexplored areas.

**Comment by obble** [comment]
Closing this for now to keep my issues feed clean around release :o)
