### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by WrobotProfiles** [obble/modui_classic#12]
was really hoping to use this =(

But when i got in the game, shit was allll sorts of fucked up

https://i.imgur.com/YygEZtI.jpg

Couoldnt open bags, couldnt do much of anything -(

**Comment by Elhoej** [comment]
Same problem here. Couldn't open bags and the dark skin was missing

**Comment by obble** [comment]
Latest version just uploaded should resolve this.

**Comment by Elhoej** [comment]
Oh cool, thank you! Will you be implementing all the futures from the private server version?

**Comment by obble** [comment]
Most stuff that was available on there should make it across. If something is missing let me know!

Closing this for now.
