### ISSUE TITLE
OneBag 

### ISSUE THREAD

**Issue by WrobotProfiles** [obble/modui_classic#13]
Hey PRO
https://i.imgur.com/Qk4U4dG.jpg

Just  a heads up =D you fixed the issue, looks good so far, however OneBag - no on off optioon,
also, i can "open: the bags": but i cannot "Close" the bags.

Also - what happend to your sexy cast bar =(

**Comment by obble** [comment]
Just put up a fix for bags that positions it a little better and gives better support for different actionbar and one-bag enabled/disabled layout options.

You can turn the one-bag off and on by toggling "Inventory" in elements.

Castbar i'd completely forgotten about tbh, i'll try add it in as it was today.

**Comment by obble** [comment]
note: inventory icons are still scaled a little weird on the standard-style mainbar - w.i.p

**Comment by Technojo01** [comment]
Really miss the sort bags functionality, think it is doable?

**Comment by obble** [comment]
added auto-sort and also fixed the bag slot icons for people using the standard-style mainbar!

**Comment by Technojo01** [comment]
You're the best! Thanks!
