### ISSUE TITLE
colour.lua error

### ISSUE THREAD

**Issue by seapunk772** [obble/modui_classic#15]
Not sure if you're aware of this.
Trying to configure addons in sandbox while in queue and I really enjoy your UI's ^^

Here's the buggrabber report:

`32x modui_classic\core/colour.lua:33: attempt to index field 'statusbar' (a nil value)
modui_classic\core/colour.lua:33: in function <modui_classic\core/colour.lua:31>
modui_classic\core/colour.lua:109: in function <modui_classic\core/colour.lua:108>

Locals:
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 11 = <table> {
 }
 13 = <table> {
 }
 PAIN = <table> {
 }
 STAGGER = <table> {
 }
 COMBO_POINTS = <table> {
 }
 FOCUS = <table> {
 }
 18 = <table> {
 }
 RUNES = <table> {
 }
 HAPPINESS = <table> {
 }
 ENERGY = <table> {
 }
 MANA = <table> {
 }
 CHI = <table> {
 }
 17 = <table> {
 }
 FURY = <table> {
 }
 HOLY_POWER = <table> {
 }
 AMMOSLOT = <table> {
 }
 INSANITY = <table> {
 }
 SOUL_SHARDS = <table> {
 }
 RUNIC_POWER = <table> {
 }
 MAELSTROM = <table> {
 }
 0 = <table> {
 }
 FUEL = <table> {
 }
 LUNAR_POWER = <table> {
 }
 ARCANE_CHARGES = <table> {
 }
 RAGE = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = "attempt to index field 'statusbar' (a nil value)"
`

**Comment by obble** [comment]
thanks, looking into this tonight

**Comment by obble** [comment]
this looks to be a cache issue. deleting your wtf with the client closed and reopening it should solve this.

please reopen this ticket if you continue having trouble after doing this.
