### ISSUE TITLE
Debuff & Quest tracker layout

### ISSUE THREAD

**Issue by Technojo01** [obble/modui_classic#16]
![Image](https://i.imgur.com/dVNxR9e.png)

**Comment by obble** [comment]
positioning fixed in the latest version, i've parented debuffs directly to the left of the QuestWatchFrame so they should never collide:

<img width="359" alt="Screenshot 2019-08-28 at 08 18 50" src="https://user-images.githubusercontent.com/96432/63835618-ba8f0a00-c96f-11e9-8f24-ad865179ee0e.png">
