### ISSUE TITLE
Feature request: Energy ticks

### ISSUE THREAD

**Issue by Xerugos** [obble/modui_classic#18]
Hey mate!
Can you add the feature to see energy ticks on the energy bar, like in the vanilla modui addon. Was really handy and missing that feature so much!:)
Thanks in advance!

**Comment by obble** [comment]
yes! on my to-do list for this week

**Comment by Xerugos** [comment]
Cheers!

**Comment by Xerugos** [comment]
Ohh and an issue aswell. Combo points on nameplates are bugged. Usually only shows one cp 80% of the times even tho i have multiple combo points on the target.

**Comment by obble** [comment]
those damn combo points. looking into it!

**Comment by obble** [comment]
added in the latest version here, issues with combo points *should* also be solved - with the layout now matching the older modui design
