### ISSUE TITLE
Health Bars

### ISSUE THREAD

**Issue by WrobotProfiles** [obble/modui_classic#19]
https://i.imgur.com/4m53pGQ.jpg

Not sure if this is related to modui or UnitFramedImproved .. but thought id show you -look at my character top left

**Comment by WrobotProfiles** [comment]
Also - Wanted to let you know, that when you Hover over a mob and have skinning - it doesnt show the "skinning color" hehe

**Comment by seapunk772** [comment]
You have two addons modifying the same thing, They are confuse

Go to: 
>ModUI settings
>Unit
>Disable Player/Target/Party/Party/TargetofTarget

Now if you find a way to integrate just the UnitFramesImproved textures into ModUI,
that'd be great.
I tried but idk wtf I'm doing
I'm used to editing vanilla and tbc lua scripts. not this new stuff

**Comment by obble** [comment]
yeah you need to disable modui unitframes if you're using another addon to mod them.

i'd also noticed the skinning thing last night, probably being caused by me rebuilding the tooltip information - i'll fix it asap.
