### ISSUE TITLE
ActionBars  from 1.12

### ISSUE THREAD

**Issue by Shortlord** [obble/modui_classic#20]
heey ;-)  I use your addon over years on private servers and love it ! but i got one question. 

is it possible that you can put in the option  that the actions bars from the right side are in the middle too ?   like in this picture? 

sorry for my bad english :D 

![WoWScrnShot_011618_000729](https://user-images.githubusercontent.com/54649891/63900281-56685680-ca00-11e9-9abc-db54f29a1761.jpg)

**Comment by Elhoej** [comment]
I would like this as well.

**Comment by obble** [comment]
Heh, i'd completely forgotten this was an option in 1.12. Yeah i'll look at adding it soon.

**Comment by Shortlord** [comment]
cool !! thank you so much :3

**Comment by Elhoej** [comment]
Awesome!

**Comment by wesker3** [comment]
Ye, we need it. Thanks!

**Comment by obble** [comment]
Added in the latest version, note that you need to disable the BfA-style actionbar layout in the elements menu for it to work.

**Comment by Shortlord** [comment]
thank you very very much for adding the actionBar from classic :3  
the only issue i have now is that my StanceBar from my Warrior is behind the added ActionBar. 
can you fix that? its not a big issue for me but i thought i told you about that :)
