### ISSUE TITLE
UI Colors doesn't load properly

### ISSUE THREAD

**Issue by Elhoej** [obble/modui_classic#24]
When I change the UI Color from ModUI Menu, they don't load properly when I relog. If I go to the color settings I can see that they have the correct value that I set them to, but it doesn't load except if I move the sliders again.

**Comment by obble** [comment]
with your client closed can you delete your WTF folder and restart the game? this is likely an issue with saved variables not saving correctly.

let me know if the issues persist after this.

**Comment by obble** [comment]
closing this to consolidate issue tickets regarding people's problems with the UI colours, see https://github.com/obble/modui_classic/issues/24
