### ISSUE TITLE
UI Colour & Saved Variable issues

### ISSUE THREAD

**Issue by rfdunn** [obble/modui_classic#25]
I realise this is a work in progress, and for that I thank you. I get an entirely blank window when selecting ModUI Elements, and have no minimap icon.

Should I be expecting these? Or is it simply not ready yet? Thanks!

**Comment by Starcheck** [comment]
Hey,

the last fix regarding Beta Bugs was better but I still get some major errors.
This is how it looks like.

![WoWScrnShot_082919_152046](https://user-images.githubusercontent.com/54445661/63943821-b0086980-ca70-11e9-9c3f-89f68993a73e.jpg)

Last time you said I should run a command and let you know whats wrong. It gives me 27 LUA errors that I copy pasted for you:

https://pastebin.com/0AKTDzH1

thanks again!

**Comment by obble** [comment]
exciting bugs! looks like its an issue with saved variables not being saved correctly. with your client closed can you delete your WTF folder and restart the game? I realise this is a pain with the current queue Armageddon :(

let me know if the issues persist after this.

**Comment by Starcheck** [comment]
Thanks @obble 

Indeed deleting the 2 savedVAriable files regarding modUi in WTF was solving all my issues! Im looking forward for your updated on adding new elements!

Amating work ty!

**Comment by rfdunn** [comment]
What command do I need to run to get a dump of the LUA errors?

**Comment by rfdunn** [comment]
Sadly deleting the WTF folder did not work for me, it's still not working.

**Comment by WrobotProfiles** [comment]
shring your UI scale

**Comment by obble** [comment]
_/console scriptErrors 1_ enables LUA errors in-game.

Can you try the following?

Navigate to: WTF/Account/_string of numbers relating to account profile_/_your server name_/_your character name_/SavedVariables/modui_classic.lua

Open this file up in a text editor and overwrite the text in it with the following:

`MODUI_VAR = {
	["elements"] = {
		["nameplate"] = {
			["friendlyclass"] = false,
			["aura"] = true,
			["enable"] = true,
			["combo"] = true,
			["totem"] = true,
		},
		["ecastbar"] = {
			["enable"] = true,
		},
		["mainbar"] = {
			["enable"] = true,
			["keypress"] = true,
		},
		["onebag"] = {
			["enable"] = true,
			["greys"] = true,
		},
		["chat"] = {
			["events"] = true,
			["enable"] = true,
			["url"] = true,
			["style"] = true,
			["sysmsg"] = false,
		},
		["tracker"] = {
			["enable"] = true,
		},
		["statusbar"] = {
			["rage"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["health"] = {
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["focus"] = {
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.25,
			},
			["mana"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 1,
			},
			["energy"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
		},
		["aura"] = {
			["enable"] = true,
			["values"] = true,
			["statusbars"] = true,
		},
		["tooltip"] = {
			["enable"] = true,
		},
		["all"] = true,
		["error"] = {
			["enable"] = false,
			["quick"] = true,
		},
		["unit"] = {
			["rcolour"] = true,
			["enable"] = true,
			["vcolour"] = true,
			["pet"] = true,
			["auras"] = true,
			["player"] = true,
			["tot"] = true,
			["target"] = true,
			["party"] = true,
		},
	},
	["statusbar"] = {
		["smooth"] = true,
	},
	["theme"] = {
		["r"] = 0,
		["g"] = 0,
		["b"] = 0,
	},
	["theme_bu"] = {
		["r"] = 0,
		["g"] = 0,
		["b"] = 0,
	},
}`

Then do the same with the modui_classic.lua.bak file in the same directory.

Reload and let me know if that does anything for you?

**Comment by obble** [comment]
oh no i think i just found the problem, and its a stupid one

**Comment by Xaero252** [comment]
I did not relog to test - though it should not be needed; but the issue persists. The colors are being loaded from the savedvariables properly as the sliders reflect the correct position, just the theming itself doesn't seem to take

**Comment by Xaero252** [comment]
Ah, I see you have some dependencies required.
After installing the dependencies it seems to work now.

for the curious you need:
LibClassicMobHealth-1.0
and
LibClassicCasterino

**Comment by Xaero252** [comment]
If those are intended to be required dependencies they should be added to the TOC imo

**Comment by obble** [comment]
thats weird, they're included as embeds in modui: https://github.com/obble/modui_classic/tree/master/libraries

do you not have these in your downloaded version?

**Comment by Xaero252** [comment]
Actually just noticed that myself. I enabled lua errors and got errors about LibClassicMobHealth-1.0 and LibClassicCasterino, so I installed them and the errors are gone and it works.
The libraries are in my downloaded copy...

**Comment by obble** [comment]
Are you using other addons? If ao, can you tell me if it works when toggling those off and just leaving modui on quickly? Wondering if its an issue where something else is loading LibStub or CallbackHandler and that breaks my load of those somehow.

**Comment by obble** [comment]
ive pushed an [update](https://github.com/obble/modui_classic/commit/9e7ce1c0af117996b9d2e235d4c7423a6c814a1a) that switches to loading the libraries in an XML file (the same way Tukui does).

i also deleted the .toc file that supported people forgetting to rename the directory from modui_classic-master to modui_classic on the offchance thats messing something up.

**Comment by Xaero252** [comment]
I am - I just toggled everything off except modui; without updating to your latest commit - and everything works, which implies a conflict on my setup.
I'll update this with what the conflict is when I find it

**Comment by obble** [comment]
relog is PLAYER_LOGIN.

i noticed a bug with the colours being updated incorrectly between buttons and textures when switching between the two colour wheels, and honestly after 20 minutes of grappling with the logic for it i'm going to admit defeat and just use the single theme colour for both - one less option to worry about in the menu. this might be related to your issue - an update has been pushed for this now too, sigh.

sorry to anyone who wanted their buttons in pink but their bar in grey.

**Comment by Xaero252** [comment]
Eventually I'll poke at the logic, too. It's been a while since I did any addon coding so I'm a bit rusty with lua and wow bindings - but another set of eyes is never a bad thing.
I actually have a fork of your UI for BC, privately. A bug I fixed there is present here, but I'll just create a pull request when I get around to it (it's really nitpicky anyways)

**Comment by obble** [comment]
cool, nitpicky is good!

**Comment by obble** [comment]
Closing this for now seeing as reports have dwindled on it happening
