### ISSUE TITLE
Uniplates combat points

### ISSUE THREAD

**Issue by ftpn** [obble/modui_classic#28]
Combat points on uniplates not updating past first combo point.

**Comment by obble** [comment]
working on a fix for this currently

**Comment by ftpn** [comment]
So after some testing, I found that this only occurs when the first attack is a combo point generator, if I fist do an auto attack it will update combo points correctly.
Hope it helps finding a fix.

**Comment by Liathwasted** [comment]
This must be very useful input for @obble. Well done @ftpn

**Comment by obble** [comment]
I *think* this is fixed now, everything working in my testing session today - i also reverted the style back to the more classic modui layout.

please re-open this ticket if issues persist.
