### ISSUE TITLE
Error on Login - Thought id let u know

### ISSUE THREAD

**Issue by WrobotProfiles** [obble/modui_classic#29]
Scratch - Auctioneer caused it...

https://i.imgur.com/hw9FX1w.png

Is the new issue, need a bit more spacing

**Comment by WrobotProfiles** [comment]
nvm i think its cause of another addon,

https://i.imgur.com/hw9FX1w.png


However - ur buffs need to be moved down

**Comment by obble** [comment]
should be fixed in latest version, i bumped up the vertical padding
