### ISSUE TITLE
Would love this pack for classic 

### ISSUE THREAD

**Issue by Mezq** [obble/modui_classic#3]
So i tried also downloading the pack for the stress-test, sadly it didnt work i would love if you "obble" could bring this back to life, its probably the best pack out there.

**Comment by obble** [comment]
Hey there, the stress test was the first chance to test my code (written on retail servers) and several elements needed fixing. a stable-ish version has just been pushed that i'll continue to refine in the next few weeks up to the release date.

**Comment by Nelythia** [comment]
Will it be designed like the current 1.12.1 version?
I especially loved the player frames as well as how it dispalyed health & resource values in it's own colors.

**Comment by obble** [comment]
there will be some changes and improvements (such as the introduction of the size-changing mainmenubar from wow 8.0) but it will mostly stay the same.

Unitframes are still mostly to-do, and yeah - working on that menu today when I get a chance :)

**Comment by Mezq** [comment]
obble thanks for the great news and also i appreciated ur effort of pushing this out as fast as you can.

**Comment by AmplusNLD** [comment]
Hi Obble, I just found out that you are working on the Classic version of Modui. 
I just gave it a spin on the stress test and liked work you have put in so far.

Any chance that you will making a Discord server for this AddOn for small questions or suggestions?
So you will not get too much spam here in the issue tab of the project?

**Comment by obble** [comment]
Hey - no plans to start a discord server as id probably forget to check regularly. feel free to start an issue thread with misc. suggestions or tag them here, as I’ll likely leave this open until release

**Comment by nerox12** [comment]
Hey man loved this addon on 1.12 used it forever. How come it has the BFA ui for classic though? Would really really love to have it just how it was on 1.12, it was perfect.

**Comment by obble** [comment]
an option to toggle that off is coming

**Comment by Xerugos** [comment]
Hey man, just wanted to say thanks for your work so far, can't wait till you finish it!:)
I was using it for vanilla on private servers, and wouldn't be able to live without it now. And I played through original vanilla with no addons back in the days :D Only UI I ever used and ever will!
Cheers!

**Comment by Mezq** [comment]
I dont know its me or something but nothing works at all ive been trying alot renamed the Folder to Interface, i  also tried putin a AddOn folder into interface put everything inside of it still doesnt work its actualy kinda weird.

**Comment by obble** [comment]
make sure the directory is inside _World of Warcraft > _classic_ > Interface > AddOns_

Then rename the directory from _modui_classic-master_ to _modui_classic_

I'll put up a readme guide for this shortly.

**Comment by Mozziimo** [comment]
@obble Thank you so much for taking the time to restart this project for classic. I loved your UI, and looking forward to using it again.

**Comment by obble** [comment]
closing this for now as its fairly generalised feedback that has mostly been covered
