### ISSUE TITLE
PetBar Position

### ISSUE THREAD

**Issue by Bicball** [obble/modui_classic#30]
Hey there! First, Thank you for this addon and the effort to keep it updated.

The issue is about the position of the PetBar anytime the ui is reloaded (ingame portal, flight path, etc.). The PetBar is loaded behind the BottomLeftActionBar. To solve the issue we have to go into ActionBars Settings (Game Settings) and disable > enable any bar. This a minor bug, I know, but is really annoying after some time.

Thanks for your time.

**Comment by obble** [comment]
Hey, damn I thought i'd found a fix for this - i'll take another look tonight.

To confirm, the bar is initially placed correctly above the BottomLeftActionBar - but zoning or reloading sends its back to an overlapped position?

**Comment by Bicball** [comment]
Yes! Just like you said.

**Comment by obble** [comment]
Ok, hopefully just a case of finding an update to overwrite that repositioning then.

Thanks!

**Comment by Bicball** [comment]
It happened right now. I got a flight path, voidwalker was with me. When flith path finished voidwaker is gone. I summon Voidwalker again and PetBar shows behind BottomRight ActionBar.

**Comment by obble** [comment]
Think i've located the [update](https://github.com/Gethe/wow-ui-source/blob/classic/FrameXML/PetActionBarFrame.lua#L241) that is causing it so hopefully i can add a fix tonight.

**Comment by Bicball** [comment]
I think I got it too. There is a function to check if it is under ActionBar?

**Comment by obble** [comment]
re-open this ticket and let me know if this issue persists after the latest update that has just been published

**Comment by Bicball** [comment]
The addon is showing a big black rectangle above action bars. I can't see any ActionBar, even changing the color. Because when I change the color it turns green.
