### ISSUE TITLE
Buff\debuff position

### ISSUE THREAD

**Issue by JomanWalter** [obble/modui_classic#31]
Hey! Thanks for your work!
After the last update, I notice a different buff\debuff position. Buffs a bit far away from minimap I think :) And Debuffs, going totally wrong as for me. Or this is how its should be? Thanks!
Check on screen - https://prnt.sc/ozp1ol

**Comment by obble** [comment]
Hey, its unfortunately a workaround to get weapon enchants/poisons working on buffs, and avoiding overlaps with the debuffs and quest objective tracker. I don't really want to leave it laid out like this in the long term but wanted people to have these features ASAP so they could play.

So, yeah its how it should be for now. But hopefully not for too long.
