### ISSUE TITLE
May i ask some old thing pull back?

### ISSUE THREAD

**Issue by stage1st** [obble/modui_classic#33]
![2PwdWc](https://user-images.githubusercontent.com/54734593/64059832-50d46180-cbf6-11e9-98e4-6030c0a231e1.png)
![O3gYLx](https://user-images.githubusercontent.com/54734593/64059833-55007f00-cbf6-11e9-9d13-eca445d8c403.gif)
that's all i love, thanks for your work.

**Comment by WrobotProfiles** [comment]
i miss the old regular UI too, but i think it would make to much for for the creator

**Comment by obble** [comment]
black nameplate borders are in with the newest version here.

no plans to bring back the old bag/bank layout i'm afraid - it was always pretty buggy.
