### ISSUE TITLE
Energy ticker is absent in the unitframes

### ISSUE THREAD

**Issue by Liathwasted** [obble/modui_classic#34]
As described in the title, it appears that there's no timer in the modUI.

**Comment by Elhoej** [comment]
Please use the search function before creating an issue. This has already been brought up.

**Comment by Elhoej** [comment]
https://github.com/obble/modui_classic/issues/18

**Comment by Liathwasted** [comment]
Sorry, I didn't pay attention to it, since it was a feature request. My issue is more like a bug, since it existed in modUI already.
