### ISSUE TITLE
nameplates

### ISSUE THREAD

**Issue by dexterars** [obble/modui_classic#39]
![image](https://user-images.githubusercontent.com/54769273/64076444-b7787e80-cccd-11e9-9791-72dfd555b2a7.png)

**Comment by dexterars** [comment]
![image](https://user-images.githubusercontent.com/54769273/64076449-c95a2180-cccd-11e9-9146-17c46528c59c.png)

**Comment by obble** [comment]
fun one - i guess changing the statusbar texture must taint the nameplate somewhere along the line.

i'll see what can be done about this, if any change taints it I might have to rollback statusbar texture mods and leave it to players to change it in the their interface folder

**Comment by obble** [comment]
updated - reopen this ticket if issues persist in the latest version.
