### ISSUE TITLE
Pet Bar Clipping

### ISSUE THREAD

**Issue by SpaceGrape** [obble/modui_classic#4]
Pet bar is clipping, as seen in the screen shot.

Also, is there a way to make the action bar icon/buff icon borders darker?
![WoWScrnShot_081219_023158](https://user-images.githubusercontent.com/22440196/62853454-a7aae300-bca9-11e9-9bff-e177e9100dad.jpg)

**Comment by obble** [comment]
Thanks for this - totally overlooked pet & stance bars in my review last night >_<

And yeah i'd like to add support for button skin colour changing. Either matching the theme colour, offsetting it slightly, or maybe giving them a separate colour wheel for better customisation/contrast options.

**Comment by SpaceGrape** [comment]
You're doing great though! Everything else is working like a dream; keep up the amazing work. :)

**Comment by obble** [comment]
Hopefully this is now fixed! Reopen if issues persist
