### ISSUE TITLE
Energy Bar

### ISSUE THREAD

**Issue by magickbirb** [obble/modui_classic#43]
Is it possible to have an addon with separated energy bar and nothing more? And to make it start immediately after login, because right now it starts only after you've been in combat
I love how this meter works and find it extremely useful and I don't really need other mod features 
It'll be great if you separate it

Thanks!

**Comment by obble** [comment]
no plan to make it separate but you could:

1. delete every other file in the modui folder EXCEPT _unit/energy.lua_
2. open and update the **modui_classic.toc** file and replace the text contents with [this](https://gist.github.com/obble/970c6e177759a0ae281ac9a8940efd8b) code (lines 1-6).

An update tonight will enable the energy ticker on login. i'll close this ticket when its available.

**Comment by obble** [comment]
updated.
