### ISSUE TITLE
Aura Bug (Target Frame)

### ISSUE THREAD

**Issue by Bicball** [obble/modui_classic#44]
The PetBar bug was solved (thank you), but after last update I found a new bug. The auras (debuff or buff) on Target Frame don't show or don't get update eventually, even after I change target. The only solution I found /reloadui.

**Comment by obble** [comment]
I'm hoping i've found a solution to this today, will test tonight and let you know.

**Comment by obble** [comment]
i think this is fixed in the updated version, please reopen this ticket if not.
