### ISSUE TITLE
Ambiguous combo points issues

### ISSUE THREAD

**Issue by Liathwasted** [obble/modui_classic#45]
Sometimes the nameplate combo points are getting bugged, showing all the colour varieties between combo point levels and one cannot recognize how many combo points are applied.

Examples shown below

![ambiguous2](https://user-images.githubusercontent.com/54738222/64113980-726b4f80-cd94-11e9-9c27-19e4567508cd.png)

P.S. You've done great work so far and I'd like to contribute to your hard work. Is there a service you use for donations?

**Comment by dexterars** [comment]
@Liathwasted can u tell me ur fonts used ? :P

**Comment by obble** [comment]
ah, combo points :(

can you let me know how many combo points *should* have been showing in this picture, if you can remember?

**Comment by Liathwasted** [comment]
Ωχχχ βωμών φhc for I know b aph

**Comment by Liathwasted** [comment]
@obble It should be one. Let me mention that sometimes, there are no combo points applied, yet an amount is being displayed in the mobs. Once I reproduce it, I'll inform you.

**Comment by obble** [comment]
I think i might have found the issue - essentially new 5 combo points are being drawn over the old ones when a nameplate is recycled for a new unit.

I'm uploading an update that hopefully fixes the problem in a second, i'll close this ticket - reopen it if the issues persist!
