### ISSUE TITLE
Visual bug with bag incons

### ISSUE THREAD

**Issue by JomanWalter** [obble/modui_classic#48]
Hey,
That's a little bug here, after the last update
That how its look before you start to move something in your bag https://prnt.sc/p178f7 
And how its look after you move something - https://prnt.sc/p179ry

**Comment by obble** [comment]
heh yeah i spotted this doing some fishing this morning - will have a fix tonight

**Comment by JomanWalter** [comment]
Thansk you for fast respond :)

**Comment by obble** [comment]
fixed
