### ISSUE TITLE
Few issues and requests

### ISSUE THREAD

**Issue by AGandrup** [obble/modui_classic#5]
Heya obble

Glad to see that this god tier addon is making it to Classic. Tried the current version real quick before the stress test shut down and saw a few minor issue. First one that I noticed is that when using original actionbar (not bfa edition) the bags, except for bagpack, are scaled down as can be seen here: ![image](https://user-images.githubusercontent.com/43139552/62907995-12295500-bd76-11e9-8286-ee1bb8190d6e.png)
Another issue is that the addon is colliding with TinyTooltip addon. I was getting an error saying that a problem occured at line 138 in modui\tooltip\content.lua. I thought I took a screenshot of the error but I must've forgotten.

These are the only issue I experienced so far. Other than that I only have a few requests; I'd love if you could add the glow/highlight border around spell/ability icons when they are clicked, just like in the 1.12.1 version. Also would be nice if you could give icons the darker (black?) border again just like in 1.12.1 version, instead of their current grey/silver border.
I just read that you are going to make this addon pretty similar to the original so chances are that you already plan to do these things.

Anyway, thanks for your hard work. Keep it up! :-)

**Comment by Mozziimo** [comment]
I agree with the glow/highlight & the black darker border. Makes it pop and look alot better. So far so good !

**Comment by obble** [comment]
Hey there, thanks for this. 

I'm adding support for choosing to have the one-bag enabled but mainbar disabled and vice versa that causes this issue with the inventory buttonsin the next update.

The TinyTip issue *should* be solved now by toggling off the tooltip in the elements menu but let me know if it persists afterwards. I've added a fallback to this line in the next version in case TinyTip is doing something goofy like overwriting blizzard defaults.

I'll look into adding highlight/pushed button colours, and i'm going to add a second colour wheel option for choosing the colour of button borders in their normal state.

**Comment by AGandrup** [comment]
Amazing, thanks obble!

As for the tinytip issue, yes it did disappear when I unchecked tooltip option in the mod ui menu. Just thought I'd let you know anyway.

**Comment by rc4p** [comment]
Thank you "obble", you save my wow life, using modui from I found it few years ago

**Comment by AGandrup** [comment]
Hey again obble
I just thought of another thing that I'd like to see a swell which (I believe) you had in the 1.12 version and that is feature that allows the actionbar to automatically recognize which grenades and stuff like that you have in bags. So you know, if you place thorium grenades on your action bar but you run out of them, the actionbar automatically switch to iron grenades (assuming you have iron grenades in your bags obviously).

**Comment by obble** [comment]
Not sure that was ever a feature of modui but I can look into it down the line

**Comment by AGandrup** [comment]
Oh really? I could've sworn it was modui that did that. Hm, must be one of my other addons then.
Oh well, nevertheless it would be nice to have :-D
