### ISSUE TITLE
Right action bars only one button.

### ISSUE THREAD

**Issue by foobarna** [obble/modui_classic#55]
![image](https://user-images.githubusercontent.com/477645/64239905-bd5aa380-cf09-11e9-8d36-eafa6cdffe56.png)

With the latest commit **39**, the action bars on the right display only the first button. 

Any idea why?

**Comment by obble** [comment]
a coding cock-up probably, will fix ASAP tonight

**Comment by foobarna** [comment]
Ok. I thought that was some combination of options, etc.

**Comment by phendrome** [comment]
Can confirm. I have a 21.5" monitor at 1080p and having the same issue. Tried different scaling options as well. Also the "Classic" bar option and it doesn't help.

**Comment by foobarna** [comment]
I've found the issue. Will make a PR.
