### ISSUE TITLE
Healthbar, Powerbar and Class Color change options

### ISSUE THREAD

**Issue by eNtreDefias** [obble/modui_classic#6]
Hey, I was wondering if it's possible to change the colors of healthbars, powerbars and class colors? Sorry if it's already a possibility, dont have the beta so i'm not able to test the addon. The addon looks great so far tho! but if it's not possible to change the colors as i mentioned, then it would be a nice additional feature imo. I'm not the biggest fan of the default health color, and i asume there are more people who dont like it aswell. I prefere a different color darker green healthbar for example. Some may prefer a grey one etc.

**Comment by obble** [comment]
i'll look at adding a simple option for choosing custom colours on bars, maybe by changing values in the lua file itself as its probably more of a niche request compared to some other options.

**Comment by eNtreDefias** [comment]
Awesome thanks:D

**Comment by rc4p** [comment]
> i'll look at adding a simple option for choosing custom colours on bars, maybe by changing values in the lua file itself as its probably more of a niche request compared to some other options.

Hello obble, I remember there is druid bar in modui 1.12, will you add the function in this project?

**Comment by obble** [comment]
I will - I didn't get too much time to look at class specific elements in the UI (shaman totem tracking would also be nice) during the stress test but i'm keen to add these features ASAP

**Comment by obble** [comment]
Added a way to change statusbar values for advanced users in the _core/var.lua_ file under "statusbar" in the table.
