### ISSUE TITLE
Mouse tooltip 

### ISSUE THREAD

**Issue by dexterars** [obble/modui_classic#63]
I like the mouse tooltip but the fade out its long like 3-4 seconds before fadin :) can you fix it

**Comment by obble** [comment]
yeah it winds me up too! I tried and failed to find a way to fade it out quicker last night, but i'll keep this ticket open and try and locate a way to do it.

**Comment by Xaero252** [comment]
This is also a difficult problem. Even the current version of TipTac for retial lists this as a feature that needs improvement. I think I have a way to hook the underlying fade function in the BlizzardInterfaceCode - but I'm not sure that it won't cause taint.

**Comment by obble** [comment]
I guess one option might be to loop over that FadeOut function and set the alpha to 0 on the tooltip on every update. That tends not to taint compared to a show or hide call.

**Comment by Xaero252** [comment]
Even better, a bit of light reading shows that the game itself never calls GameTooltip:FadeOut and that it's there for the API only.
