### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by K0uds** [obble/modui_classic#70]
Hello,

I have this error when I log into the game 👍 

`Message: Interface\AddOns\modui_classic\core/colour.lua:37: attempt to index field 'statusbar' (a nil value)
Time: Sat Sep  7 22:46:06 2019
Count: 5
Stack: Interface\AddOns\modui_classic\core/colour.lua:37: attempt to index field 'statusbar' (a nil value)
Interface\AddOns\modui_classic\core/colour.lua:37: in function <Interface\AddOns\modui_classic\core/colour.lua:35>
Interface\AddOns\modui_classic\core/colour.lua:113: in function <Interface\AddOns\modui_classic\core/colour.lua:112>

Locals: (*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 11 = <table> {
 }
 13 = <table> {
 }
 PAIN = <table> {
 }
 STAGGER = <table> {
 }
 COMBO_POINTS = <table> {
 }
 FOCUS = <table> {
 }
 18 = <table> {
 }
 RUNES = <table> {
 }
 HAPPINESS = <table> {
 }
 ENERGY = <table> {
 }
 MANA = <table> {
 }
 CHI = <table> {
 }
 17 = <table> {
 }
 FURY = <table> {
 }
 HOLY_POWER = <table> {
 }
 AMMOSLOT = <table> {
 }
 INSANITY = <table> {
 }
 SOUL_SHARDS = <table> {
 }
 RUNIC_POWER = <table> {
 }
 MAELSTROM = <table> {
 }
 0 = <table> {
 }
 FUEL = <table> {
 }
 LUNAR_POWER = <table> {
 }
 ARCANE_CHARGES = <table> {
 }
 RAGE = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = "attempt to index field 'statusbar' (a nil value)"
`

I also have a strange bug with the chat :

![image](https://user-images.githubusercontent.com/5521628/64480092-9d550980-d1c1-11e9-80f4-f46687668e46.png)

The "Input frame" is always present ...

**Comment by K0uds** [comment]
LUA errors are gone since I deleted my save variables.

But the second issue is still present : when I press "Enter" for typing something in the chat the "Input Box" is always present (a little bit faded)

Sorry for my poor English ...

**Comment by obble** [comment]
Thanks.

Changing your chat style (interface options -> social) from IM style to Classic style should fix the issue with the chat.

Let me know if that's not the cause by reopening this ticket.
