### ISSUE TITLE
LUA error mail

### ISSUE THREAD

**Issue by s1pt** [obble/modui_classic#72]
After mail "steel lockbox" got this error. Sometimes not only on this item.

Message: Interface\AddOns\modui_classic\tooltip/content.lua:183: Usage: GetSendMailItem(sendMailIndex)
Time: Sun Sep  8 16:53:50 2019
Count: 5
Stack: Interface\AddOns\modui_classic\tooltip/content.lua:183: Usage: GetSendMailItem(sendMailIndex)
[C]: ?
[C]: in function `GetSendMailItem'
Interface\AddOns\modui_classic\tooltip/content.lua:183: in function <Interface\AddOns\modui_classic\tooltip/content.lua:182>
[C]: in function `SetSendMailItem'
Interface\FrameXML\MailFrame.lua:1088: in function `UpdateTooltip'
Interface\FrameXML\GameTooltip.lua:496: in function <Interface\FrameXML\GameTooltip.lua:475>
[C]: ?

Locals:

**Comment by Xaero252** [comment]
Looks like content.lua line 184 is probably the culprit.
Try replacing `AddPrice(count)` with `AddPrice(self, count)`
