### ISSUE TITLE
Exp bar

### ISSUE THREAD

**Issue by Dizangy** [obble/modui_classic#77]
When I dinged level 60 by exp bar turned into this 
https://gyazo.com/9b0778817346cd9a324ec8b9304b0910
It is almost double the width of my actionbar. 
Disabling exp bar does not work

**Comment by Xaero252** [comment]
Can you mouse over that bar and see if it has any data attached to it?
If not, can you run `/fstack` mouse over that bar and take a screenshot?
You can turn `fstack` back off by typing `/fstack` again.

**Comment by Dizangy** [comment]
https://gyazo.com/1940e60a1e371285f97105e286f81fdd

when hovering over it without fstack there is no information

**Comment by Xaero252** [comment]
I meant a screenshot of the `fstack` info frame. It tells us what that element is called, so we can properly handle it. iirc it's something like mainmenuinfobar or something like that. It's the BFA style bar which supports multiple reputations and other things, which is brand new to the UI code. I haven't hit 60 yet so I can't test for it. Work is frequent atm. Obble is out on holiday I believe.

**Comment by coadyduffney** [comment]
Having the same issue - heres a SS of the fstack:
https://imgur.com/a/hqqHyY6

I managed to fix it for now by running the following macro:
```
/script MainMenuMaxLevelBar:Hide()
/script MainMenuMaxLevelBar0:Hide()
/script MainMenuMaxLevelBar1:Hide()
/script MainMenuMaxLevelBar3:Hide()
```

Seems like once you hit level 60 the exp bar changes from **MainMenuExpBar** to **MainMenuMaxLevelBar**

**Comment by Redlab1** [comment]
Can confirm that what coadyduffney wrote fixes the issue temporarily.

**Comment by Redlab1** [comment]
Added a simple fix that worked for me atleast see PR https://github.com/obble/modui_classic/pull/82

**Comment by obble** [comment]
i'll give this a quick test today and then accept your pull request if it looks good.

im so behind on my levelling

**Comment by obble** [comment]
im hoping this is now fixed in the latest revision, please re-open this ticket if issues persist.
