### ISSUE TITLE
Bag keybind

### ISSUE THREAD

**Issue by Dizangy** [obble/modui_classic#78]
I have an issue where I open my bags with the default keybind (B). But i cant close them by hitting the same keybind (B).

Only by hitting escape or by clicking the bag closed.

**Comment by Xaero252** [comment]
Not able to replicate this myself - are you using any other addons?

**Comment by Dizangy** [comment]
You are correct, I thought i had all addons disabled when testing this but one slipped through the crack. This issue is not related to Modui

**Comment by ollema** [comment]
@Dizangy then please close this issue!
