### ISSUE TITLE
Toggle for classic vs bfa style action bars

### ISSUE THREAD

**Issue by kevinchesser** [obble/modui_classic#8]
Hello Obble,

First let me start with thank you for the great addon! I was wondering it you could add a toggle to switch between the classic style action bars and the bfa style compact action bars. Personally I prefer the classic action bars and I'm sure others do as well.

Thanks!

**Comment by obble** [comment]
Hi there,

You can turn this off by toggling off the "Actionbar" check button in the elements menu:

![68747470733a2f2f692e696d6775722e636f6d2f59506f416171472e6a7067](https://user-images.githubusercontent.com/96432/63207852-55146100-c0c5-11e9-8d5a-c58c79ef7df1.jpeg)

**Comment by kevinchesser** [comment]
Oh thats awesome. Thanks!
