### ISSUE TITLE
Experience bar issue at 60

### ISSUE THREAD

**Issue by bobotheklown** [obble/modui_classic#91]
After hitting level 60, the XP bar goes away and in its place leaves a thin black bar extending from the sides of the action bars.

Screenshot attached
![ss+(2019-09-20+at+06 12 55)](https://user-images.githubusercontent.com/54679540/65365896-78559300-dbd2-11e9-9788-5624a1e17e98.jpg)

**Comment by Xaero252** [comment]
Duplicate of #77
