### ISSUE TITLE
Unitframes health and resource bars not being skinned

### ISSUE THREAD

**Issue by jwbaldwin** [obble/modui_classic#92]
Hey!

First, great job with the addon, I am loving it!

I'm having an issue that may be an easy fix. The health and resource are not being skinned the same as the name is. It seems to be defaulting to Blizzard's standard. I've disabled any addon I thought my be overriding but still remains. 

Let me know if you need anything from me.

![Capture](https://user-images.githubusercontent.com/16193332/65643629-32c50b80-dfc0-11e9-9722-ed3256f0bdd7.PNG)

**Comment by obble** [comment]
this was intentionally rolled back due to issues with the addon tainting. i'm still looking into fixing it

**Comment by jwbaldwin** [comment]
Ah. I see. Thanks for the response @obble!
